### ISSUE TITLE
Can't find train/test split for Scenario 1

### ISSUE THREAD

**Issue by Multihuntr** [Orion-AI-Lab/S4A#3]
This is advertised as a benchmark dataset. To be a benchmark, it needs to have a well-defined train/test split, but I can't find the train/test splits you used for Scenario 1 from your paper. Without the split, it is difficult to compare methods.

**Comment by paren8esis** [comment]
Hello,

The COCO files defining the splits for each scenario are provided in the [S4A-Models](https://github.com/Orion-AI-Lab/S4A-Models) repo. Since this wasn't clear, we added the link to this README file too. You can find all splits as well as model weights [here](https://www.dropbox.com/sh/kvgo4r2vin7sbwt/AACzDLNbnSouuZYMk8Y9I4sha?dl=0).

**Comment by Multihuntr** [comment]
Many thanks!
